repos:
- repo: https://github.com/hakancelik96/unimport
  rev: 0.8.3
  hooks:
    - id: unimport
      args: [-r]
-   repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
    -   id: isort
-   repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
    - id: black
      args: [--safe, --quiet]
- repo: https://github.com/dfm/black_nbconvert
  rev: v0.4.0
  hooks:
  - id: black_nbconvert
- repo: https://github.com/kynan/nbstripout
  rev: 0.7.1
  hooks:
    - id: nbstripout
      args: [--max-size 1k]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: check-merge-conflict
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-json
    -   id: check-yaml
- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.5.2
  hooks:
    - id: nbqa-pyupgrade
      args: [--py38-plus]
      additional_dependencies: [pyupgrade, ipython~=8.12.0]
    - id: nbqa
      entry: nbqa unimport
      name: Detect unused imports
      alias: nbqa-unimport
      additional_dependencies: [unimport==0.12.1, ipython~=8.12.0]
      args: [--check]
    - id: nbqa-isort
      args: [--float-to-top]
      additional_dependencies: [isort, ipython~=8.12.0]
    - id: nbqa-flake8     #  the config does not seem to be read for the moment  # todo
      args: [--config=./.flake8, '--ignore=E203,W503,E231,E501']
      additional_dependencies: [flake8==3.8.4, ipython~=8.12.0]
- repo: https://github.com/nbQA-dev/nbQA
  rev: 0.5.9
  hooks:
    - id: nbqa-isort
      args: [--nbqa-mutate]
- repo: https://github.com/PyCQA/flake8
  rev: 3.8.4
  hooks:
    -   id: flake8
        args: [--config=.flake8]
-   repo: local
    hooks:
    -   id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args: [--errors-only]
